.class public Lorg/pf4j/processor/LegacyExtensionStorage;
.super Lorg/pf4j/processor/ExtensionStorage;


# static fields
.field public static final EXTENSIONS_RESOURCE:Ljava/lang/String; = "META-INF/extensions.idx"


# direct methods
.method public constructor <init>(Lorg/pf4j/processor/ExtensionAnnotationProcessor;)V
    .registers 2

    invoke-direct {p0, p1}, Lorg/pf4j/processor/ExtensionStorage;-><init>(Lorg/pf4j/processor/ExtensionAnnotationProcessor;)V

    return-void
.end method


# virtual methods
.method public read()Ljava/util/Map;
    .registers 6

    new-instance v1, Ljava/util/HashMap;

    invoke-direct {v1}, Ljava/util/HashMap;-><init>()V

    :try_start_5
    invoke-virtual {p0}, Lorg/pf4j/processor/LegacyExtensionStorage;->getFiler()Ljavax/annotation/processing/Filer;

    move-result-object v0

    sget-object v2, Ljavax/tools/StandardLocation;->CLASS_OUTPUT:Ljavax/tools/StandardLocation;

    const-string v3, ""

    const-string v4, "META-INF/extensions.idx"

    invoke-interface {v0, v2, v3, v4}, Ljavax/annotation/processing/Filer;->getResource(Ljavax/tools/JavaFileManager$Location;Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljavax/tools/FileObject;

    move-result-object v0

    new-instance v2, Ljava/util/HashSet;

    invoke-direct {v2}, Ljava/util/HashSet;-><init>()V

    const/4 v3, 0x1

    invoke-interface {v0, v3}, Ljavax/tools/FileObject;->openReader(Z)Ljava/io/Reader;

    move-result-object v0

    invoke-static {v0, v2}, Lorg/pf4j/processor/ExtensionStorage;->read(Ljava/io/Reader;Ljava/util/Set;)V

    const/4 v0, 0x0

    invoke-interface {v1, v0, v2}, Ljava/util/Map;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    :try_end_24
    .catch Ljava/io/FileNotFoundException; {:try_start_5 .. :try_end_24} :catch_33
    .catch Ljava/nio/file/NoSuchFileException; {:try_start_5 .. :try_end_24} :catch_35
    .catch Ljavax/annotation/processing/FilerException; {:try_start_5 .. :try_end_24} :catch_31
    .catch Ljava/io/IOException; {:try_start_5 .. :try_end_24} :catch_25

    :goto_24
    return-object v1

    :catch_25
    move-exception v0

    invoke-virtual {v0}, Ljava/io/IOException;->getMessage()Ljava/lang/String;

    move-result-object v0

    const/4 v2, 0x0

    new-array v2, v2, [Ljava/lang/Object;

    invoke-virtual {p0, v0, v2}, Lorg/pf4j/processor/LegacyExtensionStorage;->error(Ljava/lang/String;[Ljava/lang/Object;)V

    goto :goto_24

    :catch_31
    move-exception v0

    goto :goto_24

    :catch_33
    move-exception v0

    goto :goto_24

    :catch_35
    move-exception v0

    goto :goto_24
.end method

.method public write(Ljava/util/Map;)V
    .registers 8

    const/4 v5, 0x0

    :try_start_1
    invoke-virtual {p0}, Lorg/pf4j/processor/LegacyExtensionStorage;->getFiler()Ljavax/annotation/processing/Filer;

    move-result-object v0

    sget-object v1, Ljavax/tools/StandardLocation;->CLASS_OUTPUT:Ljavax/tools/StandardLocation;

    const-string v2, ""

    const-string v3, "META-INF/extensions.idx"

    const/4 v4, 0x0

    new-array v4, v4, [Ljavax/lang/model/element/Element;

    invoke-interface {v0, v1, v2, v3, v4}, Ljavax/annotation/processing/Filer;->createResource(Ljavax/tools/JavaFileManager$Location;Ljava/lang/CharSequence;Ljava/lang/CharSequence;[Ljavax/lang/model/element/Element;)Ljavax/tools/FileObject;

    move-result-object v0

    new-instance v1, Ljava/io/BufferedWriter;

    invoke-interface {v0}, Ljavax/tools/FileObject;->openWriter()Ljava/io/Writer;

    move-result-object v0

    invoke-direct {v1, v0}, Ljava/io/BufferedWriter;-><init>(Ljava/io/Writer;)V
    :try_end_1b
    .catch Ljava/io/FileNotFoundException; {:try_start_1 .. :try_end_1b} :catch_59
    .catch Ljavax/annotation/processing/FilerException; {:try_start_1 .. :try_end_1b} :catch_5f
    .catch Ljava/io/IOException; {:try_start_1 .. :try_end_1b} :catch_66

    :try_start_1b
    const-string v0, "# Generated by PF4J"

    invoke-virtual {v1, v0}, Ljava/io/BufferedWriter;->write(Ljava/lang/String;)V

    invoke-virtual {v1}, Ljava/io/BufferedWriter;->newLine()V

    invoke-interface {p1}, Ljava/util/Map;->entrySet()Ljava/util/Set;

    move-result-object v0

    invoke-interface {v0}, Ljava/util/Set;->iterator()Ljava/util/Iterator;

    move-result-object v2

    :cond_2b
    invoke-interface {v2}, Ljava/util/Iterator;->hasNext()Z

    move-result v0

    if-eqz v0, :cond_5b

    invoke-interface {v2}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Ljava/util/Map$Entry;

    invoke-interface {v0}, Ljava/util/Map$Entry;->getValue()Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Ljava/util/Set;

    invoke-interface {v0}, Ljava/util/Set;->iterator()Ljava/util/Iterator;

    move-result-object v3

    :goto_41
    invoke-interface {v3}, Ljava/util/Iterator;->hasNext()Z

    move-result v0

    if-eqz v0, :cond_2b

    invoke-interface {v3}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Ljava/lang/String;

    invoke-virtual {v1, v0}, Ljava/io/BufferedWriter;->write(Ljava/lang/String;)V

    invoke-virtual {v1}, Ljava/io/BufferedWriter;->newLine()V
    :try_end_53
    .catch Ljava/lang/Throwable; {:try_start_1b .. :try_end_53} :catch_54
    .catch Ljava/io/FileNotFoundException; {:try_start_1b .. :try_end_53} :catch_59
    .catch Ljavax/annotation/processing/FilerException; {:try_start_1b .. :try_end_53} :catch_5f
    .catch Ljava/io/IOException; {:try_start_1b .. :try_end_53} :catch_66

    goto :goto_41

    :catch_54
    move-exception v0

    :try_start_55
    invoke-virtual {v1}, Ljava/io/BufferedWriter;->close()V
    :try_end_58
    .catch Ljava/lang/Throwable; {:try_start_55 .. :try_end_58} :catch_61
    .catch Ljava/io/FileNotFoundException; {:try_start_55 .. :try_end_58} :catch_59
    .catch Ljavax/annotation/processing/FilerException; {:try_start_55 .. :try_end_58} :catch_5f
    .catch Ljava/io/IOException; {:try_start_55 .. :try_end_58} :catch_66

    :goto_58
    :try_start_58
    throw v0

    :catch_59
    move-exception v0

    :goto_5a
    return-void

    :cond_5b
    invoke-virtual {v1}, Ljava/io/BufferedWriter;->close()V

    goto :goto_5a

    :catch_5f
    move-exception v0

    goto :goto_5a

    :catch_61
    move-exception v1

    invoke-virtual {v0, v1}, Ljava/lang/Throwable;->addSuppressed(Ljava/lang/Throwable;)V
    :try_end_65
    .catch Ljava/io/FileNotFoundException; {:try_start_58 .. :try_end_65} :catch_59
    .catch Ljavax/annotation/processing/FilerException; {:try_start_58 .. :try_end_65} :catch_5f
    .catch Ljava/io/IOException; {:try_start_58 .. :try_end_65} :catch_66

    goto :goto_58

    :catch_66
    move-exception v0

    invoke-virtual {v0}, Ljava/io/IOException;->toString()Ljava/lang/String;

    move-result-object v0

    new-array v1, v5, [Ljava/lang/Object;

    invoke-virtual {p0, v0, v1}, Lorg/pf4j/processor/LegacyExtensionStorage;->error(Ljava/lang/String;[Ljava/lang/Object;)V

    goto :goto_5a
.end method
